chest_items:
  weapons:
    DIAMOND_SWORD: 1
    IRON_SWORD: 1
    BOW: 1
  blocks:
    DIAMOND_BLOCK: 16
    IRON_BLOCK: 16
    BOOKSHELF: 16
  food:
    APPLE: 16
    BREAD: 16
    COOKED_BEEF: 16
  other:
    DIAMOND: 8
    GOLD_INGOT: 8
    REDSTONE: 8

trails:
  fire_trail:
    name: "Testovskiy"
    material: BLAZE_POWDER
    particle: VILLAGER_ANGRY
  water_trail:
    name: "Testovskiy2"
    material: BLAZE_POWDER
    particle: CRIT_MAGIC

kits:
  assassin:
    name: "Асассин"
    icon: WOODEN_SWORD
    items:
      WOODEN_SWORD:
        quantity: 1
        enchantment: DAMAGE_ALL
        enchantment_level: 2


